name: Update NFL Scores

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggers

jobs:
  update-scores:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use Node.js 18 or higher

      - name: Install dependencies
        working-directory: nfl-scores  # Set working directory to nfl-scores
        run: npm install

      - name: Run scrapeScores.js script
        working-directory: nfl-scores  # Set working directory to nfl-scores
        run: node scrapeScores.js

      - name: Run calculateScores.js script
        run: node calculateScores.js

      - name: List files in nfl-scores directory
        working-directory: nfl-scores
        run: ls -la

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions'
          author_email: 'github-actions@github.com'
          message: 'Update scores'
          add: 'winners.json leaderboard.json'  # Include both JSON files with the correct paths
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
